"""
Module 6 — Quality Validation.

Runs 10 ffprobe-based checks on the final output video, embeds metadata,
generates a rich console report, and writes validation_report.json.
"""
from __future__ import annotations

import json
import logging
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from src.project_manager import update_pipeline_status
from src.utils.json_schemas import (
    ModuleStatus,
    ValidationCheck,
    ValidationReport,
)

logger = logging.getLogger(__name__)

# Tolerances
_DURATION_TOLERANCE = 0.10   # ±10%
_MIN_BITRATE_KBPS = 10
_MAX_BITRATE_KBPS = 80_000
_MIN_FILE_SIZE_MB = 0.01
_MAX_FILE_SIZE_GB = 5.0


class ValidationModule:
    def __init__(self, project_dir: Path):
        self.project_dir = Path(project_dir)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def run(self) -> ValidationReport:
        output_path = self._find_output()
        meta = self._load_project_meta()
        script_meta = self._load_script_meta()
        orch_meta = self._load_orchestration_meta()
        target_duration = float(
            orch_meta.get("total_duration_sec", 0)
            or meta.get("duration_sec", 0)
            or script_meta.get("duration_sec", 0)
        )
        title = script_meta.get("title") or meta.get("topic", "VideoForge Output")
        description = f"Generated by VideoForge. Topic: {meta.get('topic', '')}"

        probe = self.probe_output(output_path)
        checks: list[ValidationCheck] = []

        checks.append(self.check_file_exists(output_path))
        checks.append(self.check_codec(probe))
        checks.append(self.check_resolution(probe))
        checks.append(self.check_fps(probe))
        checks.append(self.check_duration(probe, target_duration))
        checks.append(self.check_bitrate(probe))
        checks.append(self.check_audio_streams(probe))
        checks.append(self.check_file_size(output_path))
        checks.append(self.check_frame_count(probe))
        checks.append(self.check_colorspace(probe))

        all_passed = all(c.passed for c in checks)
        file_size_mb = round(Path(output_path).stat().st_size / 1_000_000, 2) if Path(output_path).exists() else None

        # Embed metadata into the final file
        try:
            embedded = str(Path(output_path).with_suffix(".final.mp4"))
            self.embed_metadata(output_path, embedded, title=title, description=description)
            shutil.move(embedded, output_path)
        except Exception as e:
            logger.warning("Metadata embedding failed: %s", e)

        report = ValidationReport(
            project_id=meta.get("project_id", "unknown"),
            output_file=output_path,
            passed=all_passed,
            checks=checks,
            generated_at=datetime.now(timezone.utc).isoformat(),
            file_size_mb=file_size_mb,
        )

        self.save_report(report)
        self.print_report(report)
        self._update_status(ModuleStatus.COMPLETE)
        return report

    # ------------------------------------------------------------------
    # Story 6.1 — Individual checks
    # ------------------------------------------------------------------

    def check_file_exists(self, path: str) -> ValidationCheck:
        exists = Path(path).exists()
        return ValidationCheck(
            name="file_exists",
            passed=exists,
            expected=True,
            actual=exists,
            message="" if exists else f"Output file not found: {path}",
        )

    def check_codec(self, probe: dict) -> ValidationCheck:
        codec = self._video_stream(probe).get("codec_name", "")
        passed = "264" in codec  # h264 or h264_videotoolbox both contain "264"
        return ValidationCheck(
            name="codec_h264",
            passed=passed,
            expected="h264",
            actual=codec,
            message="" if passed else f"Expected h264, got {codec!r}",
        )

    def check_resolution(self, probe: dict) -> ValidationCheck:
        vs = self._video_stream(probe)
        w, h = int(vs.get("width", 0)), int(vs.get("height", 0))
        passed = (w == 1920 and h == 1080)
        return ValidationCheck(
            name="resolution_1080p",
            passed=passed,
            expected="1920x1080",
            actual=f"{w}x{h}",
            message="" if passed else f"Expected 1920x1080, got {w}x{h}",
        )

    def check_fps(self, probe: dict) -> ValidationCheck:
        rate_str = self._video_stream(probe).get("r_frame_rate", "0/1")
        fps = _parse_fps(rate_str)
        passed = 29 <= fps <= 31
        return ValidationCheck(
            name="fps_30",
            passed=passed,
            expected="~30",
            actual=round(fps, 2),
            message="" if passed else f"Expected ~30fps, got {fps:.2f}",
        )

    def check_duration(self, probe: dict, target_sec: float) -> ValidationCheck:
        actual = float(probe.get("format", {}).get("duration", 0))
        if target_sec <= 0:
            return ValidationCheck(name="duration", passed=True, message="No target duration set")
        tolerance = max(target_sec * _DURATION_TOLERANCE, 2.0)
        passed = abs(actual - target_sec) <= tolerance
        return ValidationCheck(
            name="duration",
            passed=passed,
            expected=round(target_sec, 1),
            actual=round(actual, 1),
            message="" if passed else f"Duration {actual:.1f}s vs target {target_sec:.1f}s (±{tolerance:.1f}s)",
        )

    def check_bitrate(self, probe: dict) -> ValidationCheck:
        br = int(probe.get("format", {}).get("bit_rate", 0)) // 1000
        passed = _MIN_BITRATE_KBPS <= br <= _MAX_BITRATE_KBPS
        return ValidationCheck(
            name="bitrate_range",
            passed=passed,
            expected=f"{_MIN_BITRATE_KBPS}k–{_MAX_BITRATE_KBPS}k",
            actual=f"{br}k",
            message="" if passed else f"Bitrate {br}k outside expected range",
        )

    def check_audio_streams(self, probe: dict) -> ValidationCheck:
        audio = [s for s in probe.get("streams", []) if s.get("codec_type") == "audio"]
        has_audio = len(audio) >= 1
        codec = audio[0].get("codec_name", "") if audio else ""
        passed = has_audio  # accept any audio codec
        return ValidationCheck(
            name="audio_stream",
            passed=passed,
            expected="≥1 audio stream",
            actual=f"{len(audio)} stream(s), codec={codec!r}",
            message="" if passed else "No audio stream found",
        )

    def check_file_size(self, path: str) -> ValidationCheck:
        try:
            size_mb = Path(path).stat().st_size / 1_000_000
        except FileNotFoundError:
            return ValidationCheck(name="file_size", passed=False, message="File not found")
        passed = _MIN_FILE_SIZE_MB <= size_mb <= (_MAX_FILE_SIZE_GB * 1000)
        return ValidationCheck(
            name="file_size",
            passed=passed,
            expected=f">{_MIN_FILE_SIZE_MB}MB",
            actual=f"{size_mb:.2f}MB",
            message="" if passed else f"File size {size_mb:.2f}MB is out of range",
        )

    def check_frame_count(self, probe: dict) -> ValidationCheck:
        vs = self._video_stream(probe)
        fps = _parse_fps(vs.get("r_frame_rate", "0/1"))
        duration = float(probe.get("format", {}).get("duration", 0))
        expected_frames = fps * duration
        if expected_frames <= 0:
            return ValidationCheck(name="frame_count", passed=True, message="Cannot compute expected frames")
        nb = int(vs.get("nb_frames") or 0)
        if nb == 0:
            # estimate from duration
            nb = int(duration * fps)
        tolerance = max(expected_frames * 0.10, 5)
        passed = abs(nb - expected_frames) <= tolerance
        return ValidationCheck(
            name="frame_count",
            passed=passed,
            expected=round(expected_frames),
            actual=nb,
            message="" if passed else f"Frame count {nb} vs expected {expected_frames:.0f}",
        )

    def check_colorspace(self, probe: dict) -> ValidationCheck:
        vs = self._video_stream(probe)
        cs = vs.get("color_space", "")
        passed = cs in ("bt709", "")  # empty means default (bt709 assumed)
        return ValidationCheck(
            name="colorspace_bt709",
            passed=passed,
            expected="bt709",
            actual=cs or "(default)",
            message="" if passed else f"Colorspace {cs!r} is not bt709",
        )

    # ------------------------------------------------------------------
    # Story 6.2 — Metadata embedding
    # ------------------------------------------------------------------

    def embed_metadata(
        self,
        input_path: str,
        output_path: str,
        title: str = "",
        description: str = "",
        keywords: str = "",
    ) -> None:
        cmd = [
            "ffmpeg", "-y",
            "-i", input_path,
            "-c", "copy",
            "-metadata", f"title={title}",
            "-metadata", f"comment={description}",
            "-metadata", f"genre={keywords}",
            "-movflags", "+faststart",
            output_path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(f"Metadata embed failed: {result.stderr[-300:]}")

    # ------------------------------------------------------------------
    # Story 6.3 — Report
    # ------------------------------------------------------------------

    def save_report(self, report: ValidationReport) -> None:
        out = self.project_dir / "validation_report.json"
        out.write_text(json.dumps(report.model_dump(), indent=2, default=str))

    def print_report(self, report: ValidationReport) -> None:
        try:
            from rich.console import Console
            from rich.table import Table
            from rich import box

            console = Console()
            status = "[green]✅ PASSED[/green]" if report.passed else "[red]❌ FAILED[/red]"
            console.print(f"\n[bold]VideoForge Quality Validation — {status}[/bold]")
            console.print(f"  File: {report.output_file}")
            if report.file_size_mb:
                console.print(f"  Size: {report.file_size_mb:.2f} MB")

            table = Table(box=box.ROUNDED, show_header=True, header_style="bold cyan")
            table.add_column("Check")
            table.add_column("Status")
            table.add_column("Expected")
            table.add_column("Actual")
            table.add_column("Notes")

            for c in report.checks:
                icon = "✅" if c.passed else "❌"
                table.add_row(
                    c.name,
                    icon,
                    str(c.expected or ""),
                    str(c.actual or ""),
                    c.message or "",
                )
            console.print(table)
            console.print()
        except Exception:
            # Graceful fallback without rich
            print(f"\nValidation {'PASSED' if report.passed else 'FAILED'}")
            for c in report.checks:
                print(f"  {'✅' if c.passed else '❌'} {c.name}: {c.message or 'OK'}")

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    def probe_output(self, path: str) -> dict:
        result = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_streams", "-show_format", path],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            return {"streams": [], "format": {}}
        return json.loads(result.stdout)

    def _video_stream(self, probe: dict) -> dict:
        return next(
            (s for s in probe.get("streams", []) if s.get("codec_type") == "video"),
            {}
        )

    def _find_output(self) -> str:
        out = self.project_dir / "output" / "final_video.mp4"
        if out.exists():
            return str(out)
        # Look for any MP4 in output/
        for mp4 in (self.project_dir / "output").glob("*.mp4"):
            return str(mp4)
        return str(out)  # will fail file_exists check

    def _load_project_meta(self) -> dict:
        p = self.project_dir / "project.json"
        return json.loads(p.read_text()) if p.exists() else {}

    def _load_script_meta(self) -> dict:
        p = self.project_dir / "script.json"
        return json.loads(p.read_text()) if p.exists() else {}

    def _load_orchestration_meta(self) -> dict:
        p = self.project_dir / "orchestration.json"
        return json.loads(p.read_text()) if p.exists() else {}

    def _update_status(self, status: ModuleStatus) -> None:
        """Update module_6_validation status directly in project.json."""
        p = self.project_dir / "project.json"
        if not p.exists():
            return
        try:
            data = json.loads(p.read_text())
            data.setdefault("pipeline", {})
            data["pipeline"]["module_6_validation"] = status.value
            from datetime import datetime, timezone
            data["updated_at"] = datetime.now(timezone.utc).isoformat()
            p.write_text(json.dumps(data, indent=2, default=str))
        except Exception as e:
            logger.warning("Could not update pipeline status: %s", e)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_fps(rate_str: str) -> float:
    try:
        if "/" in rate_str:
            n, d = rate_str.split("/")
            return float(n) / float(d) if float(d) else 0.0
        return float(rate_str)
    except (ValueError, ZeroDivisionError):
        return 0.0
